template: pib-service
deployments:
  dev:
    target: dev
    values:
      app: csapp
      namespace: csapp
      workspace: csapp
      image: ghcr.io/cse-labs/csapp:latest
      port: 8080
      nodePort: {{nodePort}}
      cpuLimit: 500m
      memoryLimit: 128Mi
      cpuRequest: 300m
      memoryRequest: 64Mi
      ingressPrefix: /csapp
      readinessProbe: /csapp/readyz
      livenessProbe: /csapp/healthz
      targets: []
