app: myapp
containerArgs: []
cpuLimit: 500m
cpuRequest: 300m
environment: dev
image: ghcr.io/cse-labs/myapp:latest
ingressPrefix: /
livenessProbe: /csapp/healthz
memoryLimit: 128Mi
memoryRequest: 64Mi
namespace: myapp
nodePort: {{nodePort}}
port: 8080
readinessProbe: /csapp/readyz
targets: []
template: pib-service
