template: pib-service
deployments:
  dev:
    target: dev
    values:
      app: csapp
      name: csapp
      namespace: csapp
      workspacespace: csapp
      image: ghcr.io/cse-labs/csapp:latest
      targets: []
      port: 8080
      nodePort: 30080
      cpuLimit: 500m
      memoryLimit: 128Mi
      cpuRequest: 300m
      memoryRequest: 64Mi
      readinessProbe: /readyz
      livenessProbe: /healthz
