app: csapp
containerArgs: []
cpuLimit: 500m
cpuRequest: 300m
environment: dev
image: ghcr.io/cse-labs/csapp:beta
ingressPrefix: /csapp/
livenessProbe: /csapp/healthz
memoryLimit: 128Mi
memoryRequest: 64Mi
namespace: csapp
nodePort: {{nodePort}}
port: 8080
readinessProbe: /csapp/readyz
targets: []
template: pib-service
