#!/bin/bash

# name: bootstrap
# short: Deploy monitoring and logging

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

kubectl apply -f "$REPO_BASE/csapp/deploy"
kubectl apply -f "$REPO_BASE/csapp/deploy/bootstrap"
kubectl apply -R -f "$REPO_BASE/csapp/deploy/bootstrap"
