#!/bin/bash

# name: clean
# short: Remove the apps from the local k3d cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

kubectl apply -f "$REPO_BASE/csapp/deploy"
kubectl apply -f "$REPO_BASE/csapp/deploy/bootstrap"
kubectl apply -R -f "$REPO_BASE/csapp/deploy/bootstrap"
