#!/bin/bash

# name: deploy
# short: Deploy the apps to the local k3d cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

# validate directories
if [ ! -d "$REPO_BASE/csapp/deploy" ]; then echo "deploy directory not found"; exit 1; fi

# create namespace
kubectl apply -f "$REPO_BASE/csapp/deploy"
kubectl apply -f "$REPO_BASE/csapp/deploy/bootstrap"
kubectl apply -R -f "$REPO_BASE/csapp/deploy/bootstrap"
#kubectl apply -R -f "$REPO_BASE/csapp/deploy"

kic build app &
kic build webv

kic pods

echo ""
echo "run 'kic pods' until the pods are running"
