apiVersion: v1
kind: Service
metadata:
  name: csapp
  namespace: csapp
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 3088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: csapp
