#!/bin/bash

cd "$REPO_BASE/csapp" || exit

# delete local deployment
kubectl delete -f deploy/app --ignore-not-found=true --wait=false

kic build app

# deploy local app and re-deploy webv
kubectl apply -f deploy
kubectl apply -f deploy/app --wait=false
