#!/bin/bash

cd "$PIB_BASE/csapp" || exit

if [ ! -d deploy/bootstrap ]
then
    echo "$PWD/deploy/bootstrap directory not found"
    exit 0
fi

# create deployment from webv-local
kubectl apply -f deploy/bootstrap
kubectl apply -R -f deploy/bootstrap
