#!/bin/bash

cd "$REPO_BASE/csapp" || exit

if [ ! -d deploy/webv ]
then
    echo "$PWD/deploy/webv directory not found"
    exit 0
fi

# delete local deployment
kubectl delete -f deploy/webv --ignore-not-found=true --wait=false

kic build webv

# create deployment from webv-local
kubectl apply -f deploy
kubectl apply -f deploy/webv --wait=false
