{
 "title": "dotnet",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": {
     "query": "label_values(http_requests_received_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(CSAppDuration_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_collection_count_total{job!=\"kubernetes-pods\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job!=\"kubernetes-pods\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job!~\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{job!~\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job!~\"kubernetes-pods\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}