###
# build commands
###

commands:
- name: build
  short: Build local apps
  scriptCommands:
    - name: all
      short: Build CSApp and WebV
      path: build/all

    - name: csapp
      short: Build CSApp
      path: build/app

    - name: webv
      short: Build WebValidate for CSApp
      path: build/webv
